name: Automatically create PR

on:
  push:
    branches:
      - feature/* # 예시: feature 브랜치에 push될 때만 동작

jobs:
  create-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_TOKEN }}
          base: main
          branch: ${{ github.ref }}
          title: "자동 PR 생성"
          body: "자동화된 PR입니다. 확인 부탁드립니다."
